### ISSUE TITLE
Summary only returning current request & limit data for last container in a pod

### ISSUE THREAD

**Issue by raspberrypython** [FairwindsOps/goldilocks#122]
When a pod contains multiple containers, the summary function and subsequently the dashboard only returns the current request and limit values for the last container in a deployment.
For example, take the following deployments:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: debian:stable-slim
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  labels:
    app: test2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: test2a
        image: debian:stable-slim
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      - name: test2b
        image: debian:stable-slim
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
  labels:
    app: test3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
    spec:
      containers:
      - name: test3b
        image: debian:stable-slim
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - name: test3a
        image: debian:stable-slim
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
```

This set of deployments results in the following summary **NB the null values for request and limits**:
```
{
  "deployments": [
    {
      "containers": [
        {
          "lowerBound": {
            "cpu": "25m",
            "memory": "262144k"
          },
          "upperBound": {
            "cpu": "48m",
            "memory": "262144k"
          },
          "target": {
            "cpu": "25m",
            "memory": "262144k"
          },
          "uncappedTarget": {
            "cpu": "25m",
            "memory": "262144k"
          },
          "limits": {
            "cpu": "1",
            "memory": "2Gi"
          },
          "requests": {
            "cpu": "500m",
            "memory": "1Gi"
          },
          "containerName": "test"
        }
      ],
      "deploymentName": "test",
      "namespace": "default"
    },
    {
      "containers": [
        {
          "lowerBound": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "upperBound": {
            "cpu": "49m",
            "memory": "131072k"
          },
          "target": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "uncappedTarget": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "limits": null,
          "requests": null,
          "containerName": "test3b"
        },
        {
          "lowerBound": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "upperBound": {
            "cpu": "49m",
            "memory": "131072k"
          },
          "target": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "uncappedTarget": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "limits": {
            "cpu": "1",
            "memory": "2Gi"
          },
          "requests": {
            "cpu": "500m",
            "memory": "1Gi"
          },
          "containerName": "test3a"
        }
      ],
      "deploymentName": "test3",
      "namespace": "default"
    },
    {
      "containers": [
        {
          "lowerBound": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "upperBound": {
            "cpu": "48m",
            "memory": "131072k"
          },
          "target": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "uncappedTarget": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "limits": null,
          "requests": null,
          "containerName": "test2a"
        },
        {
          "lowerBound": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "upperBound": {
            "cpu": "48m",
            "memory": "131072k"
          },
          "target": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "uncappedTarget": {
            "cpu": "12m",
            "memory": "131072k"
          },
          "limits": {
            "cpu": "50m",
            "memory": "128Mi"
          },
          "requests": {
            "cpu": "10m",
            "memory": "64Mi"
          },
          "containerName": "test2b"
        }
      ],
      "deploymentName": "test2",
      "namespace": "default"
    }
  ],
  "namespaces": [
    "default"
  ]
}
```

You'll see that:
- deployment "test", container "test" being the only container has a valid requests and limits.
- deployment "test2", container "test2a" has null values for requests and limits as it is not the last pod in the deployment spec.
- deployment "test3", container "test3b" has null values for requests and limits as it is also not the last pod in the deployment spec even though it has the same container configuration as "test2b".

The dashboard subsequently looks as follows **NB the Not Set values**:
<img width="473" alt="Goldilocks summary error" src="https://user-images.githubusercontent.com/2557517/75924046-2b066e80-5e5e-11ea-9e0a-b82d1bd68146.png">
