### ISSUE TITLE
Showing incorrect currently set request.memory & limit.memory value in dashboard 

### ISSUE THREAD

**Issue by Pavankumar6997** [FairwindsOps/goldilocks#274]
The currently set request/limit memory for many deployments, the value in the dashboard is showing it as `1953125Ki` for both Guaranteed & Burstable QoS

values from my deployment
```
        resources:
          limits:
            cpu: 120m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1300Mi
```

Expected to see :
```
CPU Request          100m     less than    142m
CPU Limit           120m    less than     229m
Memory Request 	1500M 	equal 	1835M
Memory Limit 	1300M	equal 	2949M
```

But Showing
```
CPU Request          100m     less than    142m
CPU Limit           120m    less than     229m
Memory Request 	1953125Ki 	equal 	1835M
Memory Limit 	1953125Ki 	equal 	2949M
```

So if the value is  `>=1000Mi` its showing as `1953125Ki`

Running with: 
Stable Goldilocks chart version: `3.1.0`
Stable VPA chart version: `0.2.1`

**Comment by Pavankumar6997** [comment]
<img width="985" alt="Screenshot 2021-01-14 at 12 15 59 PM" src="https://user-images.githubusercontent.com/47264545/104555059-37a14900-5663-11eb-9ddb-e003af24a62d.png">

**Comment by sudermanjr** [comment]
I am unable to reproduce this issue:

I set my container requests and limits as:
```
        resources:                                                     
          limits:                                                      
            cpu: 10m                                                   
            memory: 1Mi                                                
          requests:                                                    
            cpu: 10m                                                   
            memory: 1Mi                                                
```

And here's the recommendations page:

<img width="1337" alt="Screen Shot 2021-01-14 at 9 25 10 AM" src="https://user-images.githubusercontent.com/7624765/104618814-68c14f80-564a-11eb-848d-886c68c3f0b3.png">
