### ISSUE TITLE
Support for Argo Workflows

### ISSUE THREAD

**Issue by JaimeHolland** [FairwindsOps/goldilocks#558]
**Is your feature request related to a problem? Please describe.**
We use[ Argo Workflows ](https://argoproj.github.io/argo-workflows/)in my organisation, and it seems like Goldilocks does not currently support this.

The controller is currently logging out errors such as 

```
E1123 11:46:16.494795       1 controller.go:169]  "msg"="Error retrieving parent object" "error"="workflows.argoproj.io is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \"workflows\" in API group \"argoproj.io\" in the namespace \"some-namespace\""  "v1alpha1"="workflows"
E1123 11:46:16.494813       1 controller.go:64]  "msg"="An error occured retrieving the top level controller for this pod" "error"="workflows.argoproj.io is forbidden: User \"system:serviceaccount:goldilocks:goldilocks-controller\" cannot list resource \"workflows\" in API group \"argoproj.io\" in the namespace \"some-namespace\""  "abc"="def"
```

**Describe the solution you'd like**
Resources for pods generated by Argo Workflows should be analyzed by/viewable in Goldilocks

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by natikoli** [comment]
Any update about this issue? Scheduled for development in the near future?

**Comment by natikoli** [comment]
@JaimeHolland - I managed to workaround your error by implementing the following RBAC permissions:
```yaml
controller:
  rbac:
    enableArgoproj: false
    extraRules:
      - verbs:
          - 'get'
          - 'list'
          - 'watch'
        apiGroups:
          - 'argoproj.io'
        resources:
          - '*'
```
However, looks like `Goldilocks` controller still cannot scan the pods. I can the following error in the logs and think it may be related:
```
1 handler.go:41] Object has unknown type of <nil>
```
I think developers need to add the pods controller `Workflow` as an option to Goldilocks Workloads.
