### ISSUE TITLE
Failed to list *v1beta1.CronJob: the server could not find the requested resource E02

### ISSUE THREAD

**Issue by dkirrane** [FairwindsOps/goldilocks#588]
### What happened?

All Pods are up in but the `goldilocks-vpa-recommender` is failing with below. liveness probe fails and it's in a restart loop.
I'm running this locally using a kind cluster running on Docker Desktop (Windows+WSL2)

```
E0228 13:06:45.895909       1 reflector.go:178] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137: Failed to list *v1beta1.CronJob: the server could not find the requested resource
E02
```

Image `k8s.gcr.io/autoscaling/vpa-recommender:0.11.0`

### What did you expect to happen?

Expecting all pod to deploy

### How can we reproduce this?

Install the chart locally using a kind cluster.

Have the following value overrides for the helm chart:

```
      - metrics-server:
          enabled: true
          apiService:
            create: true
          extraArgs:
            - --kubelet-insecure-tls=true
            - --kubelet-preferred-address-types=InternalIP
            - --metric-resolution=40s
      - vpa:
          enabled: true
      - controller:
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      - dashboard:
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
```

### Version

goldicloack helm chart 6.5.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
