### ISSUE TITLE
Empty recommendations for operator with scale subresource 

### ISSUE THREAD

**Issue by yogeek** [FairwindsOps/goldilocks#621]
### What happened?

Hello,

some containers in goldilocks UI are empty (no recommendations displayed)

After some investigation, it seems we face the issue as described in this VPA ticket : https://github.com/kubernetes/autoscaler/issues/5836

Summary for convenience:

We use EMQX operator https://github.com/emqx/emqx-operator
It introduces a CRD called "EMQX" which has a scale subresource
When you create an "kind: EMQX" resource, the operator then creates a statefulset, which also has a scale subresource
and the result is the VPA description has the same error :
```
The targetRef controller has a parent but it should point to a topmost well-known or scalable controller
```

As the VPA is created by goldilocks, I was asked to also open an issue here.

### What did you expect to happen?

Goldilocks is able to display recommendations for any kind of workloads, whatever the controller responsible for it.

### How can we reproduce this?

Annotate a namespace with goldilocks annotation, deploy an operator that manages Custom resources with a scale subresource (like EMQX operator for example) and check that VPA has an error about the controller targetRef and that goldilocks does not display any information about the workload.

### Version

4.8.3

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Thanks for the report, we'll have to work on reproducing this and see what's up with our logic that finds the top-level controller

**Comment by rbren** [comment]
@yogeek you likely need to add RBAC to grant Goldilocks access to those resources. If you're deploying via Helm, you can use `.controller.rbac.extraRules`

**Comment by akelge** [comment]
The same happens to me with Prometheus, Alertmanager and some Longhorn resources and the issue is exactly as described. Goldilock goes up the set of resources and find the top most that is not supported by VPA.
For example, for prometheus pod it finds the related STS, that is created by a Prometheus Custom Resource, the VPA is created as it follows
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    creator: Fairwinds
    source: goldilocks
  name: goldilocks-promstack-prometheus
  namespace: monitoring
spec:
  targetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: promstack-prometheus
  updatePolicy:
    updateMode: "Off"
 ```
note that`spec.targetRef.kind` is `Prometheus` while it should be `StatefulSet`.

This issue seems to be related to https://github.com/FairwindsOps/goldilocks/issues/500 that has been closed in October 2022, with no apparent solution. I checked https://github.com/fairwindsops/controller-utils but I could not find any mention of the current issue
