### ISSUE TITLE
Add controller flags to fine-tune the creation of VPA objects

### ISSUE THREAD

**Issue by asenyaev** [FairwindsOps/goldilocks#649]
Currently, there are [some variants](https://goldilocks.docs.fairwinds.com/advanced/#flags) where VPA should be created by goldilocks. This works for all resources in the namespace, but sometimes an object shouldn't have VPA object and an ability to scale.

I would like to suggest an enhancement to create a flag / annotation to control specific resources.

Example using `helm` (new flag - `exclude-resources`):

```yaml
controller:
  flags:
    on-by-default: false
    include-namespaces: ["application"]
    exclude-namespaces: ["kube-system"]
    exclude-resources: ["rabbitmq-cluster"]
```

In this case, all resources in the `application` namespace will have VPA objects except the `rabbitmq-cluster` object (statefulset / deployment).

This enhancement could temporarily solve issues when VPA cannot work with specific CRDs:
- https://github.com/FairwindsOps/goldilocks/issues/621
- https://github.com/kubernetes/autoscaler/issues/6120
