### ISSUE TITLE
basePath is not being honored for static assets, e.g. CSS and Images

### ISSUE THREAD

**Issue by stormmore** [FairwindsOps/goldilocks#652]
### What happened?

setting the base path doesn't change the href for images and css

### What did you expect to happen?

images and css to be downloaded and rendered

### How can we reproduce this?

setg basePath

### Version

4.10.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Stevie was able to reproduce this. We'll take a look

**Comment by karimarous** [comment]
Hello, just curious to know when this bug will be fixed?

**Comment by ericksoncl23** [comment]
I'm having the same problem. 
Doesn't work 404- https://<url>/goldilocks
I get this page but all images and css is broken - https://<url>/goldilocks/namespaces

The images do exist under /goldilocks/static/images/goldilocks.svg
However the dashboard page is only linking to /static/images/goldilocks.svg

**Comment by karimarous** [comment]
Still facing the same issue. I'm using the latest helm version 8.0.1

**Comment by BzSpi** [comment]
Is there any previous version that works waiting for the fix ?

**Comment by julian-vp** [comment]
As a workaround one can use another Ingress with a similar configuration:  

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /goldilocks/static/$1/$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
  name: fairwinds-goldilocks-static
spec:
  rules:
    - host: your.host
      http:
        paths:
          - backend:
              service:
                name: fairwinds-goldilocks-dashboard
                port:
                  name: http
            path: /static/(css|images|js|webfonts)/(.*)$
            pathType: ImplementationSpecific
...
```
