### ISSUE TITLE
Wrong "current" shown for memory in dashboard

### ISSUE THREAD

**Issue by apamildner** [FairwindsOps/goldilocks#668]
### What happened?

I'm trying to use goldilocks and see the recommended settings, this is the requests on my pod:
![image](https://github.com/FairwindsOps/goldilocks/assets/10640074/5915f363-0d31-42e6-8c71-c9781190d0bb)

This is how the VPA that was created looks:
![image](https://github.com/FairwindsOps/goldilocks/assets/10640074/0d0d44ff-a347-45fd-b90d-91e27b0f2192)

This is how the dashboard reports it:
![image](https://github.com/FairwindsOps/goldilocks/assets/10640074/adc8df12-79a1-4f61-869e-3eb28474e10f)

I don't think the memory value for "current" is correct, or what am I missing here?

### What did you expect to happen?

I expect the "current" settings to be the same as what I have put on the pod

### How can we reproduce this?

Hard to say, this is my values file for VPA:

```yaml

# This is important, its what makes it run only in recommender mode
updater:
  enabled: false

# This is important, its what makes it run only in recommender mode
admissionController:
  enabled: false

```

This is the values for goldilocks:
```yaml
vpa:
  enabled: false

metrics-server:
  # metrics-server.enabled -- If true, the metrics-server will be installed as a sub-chart
  enabled: false

controller:
  # controller.resources -- The resources block for the controller pods
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 25m
      memory: 256Mi
dashboard:
  # dashboard.enabled -- If true, the dashboard component will be installed
  enabled: true

  # dashboard.excludeContainers -- Container names to exclude from displaying in the Goldilocks dashboard
  excludeContainers: "containerA,containerB"

  # dashboard.resources -- A resources block for the dashboard.
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 25m
      memory: 256Mi

```

### Version

Versions: **Goldilocks helm chart**
```
repository       = "https://charts.fairwinds.com/stable"
chart = "goldilocks" 
version          = "8.0.0" 
```
**VPA** 
```
repository       = "https://charts.fairwinds.com/stable"
chart = "vpa"
version          = "3.0.2"
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
